###GET
GET https://api.e-biddi.com/api/auction/69889

###GET
GET https://api.e-biddi.com/api/events/1160

###GET

GET https://api.e-biddi.com/api/contract/event/69889

###GET
GET https://api.e-biddi.com/api/auction/reauctioneventitem

###POST
POST https://api.e-biddi.com/api/auth/login
# Content-Type: application/x-www-form-urlencoded
Content-Type: application/json

{
    "username":"012345678900",
    "password" : "12345"
}
###POST
POST https://api.e-biddi.com/api/auth/verify
Content-Type: application/json

{
    "verification_token":"",
    "verification_pin" : "12345"
}

###POST
POST https://api.e-biddi.com/api/auth/pin/refresh
Content-Type: application/json

{
    "verification_token":"eyJpdiI6IjRlVXRqRXF4TTJkazRISG0reFY2THc9PSIsInZhbHVlIjoiTmhyeVwvVjNMQ3J3UnlUQXR1T3A2OGc9PSIsIm1hYyI6ImQ0ODdkZDIzNDg4MzI5YWYzZTQwMDE1YzY3ODI5MDg4OWVjMTA3YzcxZTVmYWI3MGNiMGVjM2E4MDA0YzY0NzIifQ=="
}
###POST
POST https://api.e-biddi.com/api/auction/agreement/confirm
Content-Type: application/json

{
    "user_id": 232,
    "event_id": 1141

}
###POST
POST https://api.e-biddi.com/api/auction/agreement/verify
Content-Type: application/json

{
    "user_id": 232,
    "event_id": 1141
}

###POST
POST https://api.e-biddi.com/api/profile/232/changeemail
Content-Type: application/x-www-form-urlencoded

email=dev@tes1t.com,


#REAUCTION

###GET REAUCTION LIST
GET https://api.e-biddi.com/api/auction/reauction/item/event/1146
###GET REAUCTION STATUS
GET https://api.e-biddi.com/api/auction/reauctionevent/event/1146
###GET REAUCTION HOLD ITEM
GET https://api.e-biddi.com/api/auction/item/event/1146/hold
