// START(1), RUN(2), END(3), PAUSE(4), WITHDRAW(5), CLOSE(6), HOLD(7)
export type Status =
  | ""
  | "SOLD"
  | "REAUCTIONLIST"
  | "REAUCTION"
  | "REAUCTIONITEM"
  | "REAUCTIONLISTITEM"
  | "REAUCTIONLISTUPDATE"
  | "REAUCTIONLISTUPDATETIMER"
  | "AUCTION"
  | "START"
  | "RUN"
  | "END"
  | "PAUSE"
  | "WITHDRAW"
  | "CLOSE"
  | "DISPLAY"
  | "HOLD";
